MyFirstWebApp/MyFirstWebApp/Models/GradeCalcModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyFirstWebApp.Models
{
    public class GradeCalcModel
    {
        // Defines getters and setters for each element of the form, validates that the number inputed is between 0 and 100.
        [Range(0,100, ErrorMessage = "Can only be between 0 and 100")]
        public int Assignments { get; set; }
        [Range(0, 100, ErrorMessage = "Can only be between 0 and 100")]
        public int GroupProject { get; set; }
        [Range(0,100, ErrorMessage = "Can only be between 0 and 100")]
        public int Quizzes { get; set; }
        [Range(0, 100, ErrorMessage = "Can only be between 0 and 100")]
        public int MidtermExam { get; set; }
        [Range(0, 100, ErrorMessage = "Can only be between 0 and 100")]
        public int FinalExam { get; set; }
        [Range(0, 100, ErrorMessage = "Can only be between 0 and 100")]
        public int INTEX { get; set; }
    }
}

MyFirstWebApp/MyFirstWebApp/Controllers/BlahController.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyFirstWebApp.Controllers
{
    public class BlahController : Controller
    {
        //when the index page is called, it returns the index view.
        public IActionResult Index()
        {
            return View();
        }

        //get request to display the Grade Calculator page
        [HttpGet]
        public IActionResult GradeCalc ()
        {
            return View();
        }

        //post request to post the Grade Calculator input to the attached model.
        [HttpPost]
        public IActionResult GradeCalc (GradeCalcModel model)
        {
            return View();
        }
    }
}

MyFirstWebApp/MyFirstWebApp/Views/Blah/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    // Razor code sets text in the header, changes the layout title section
    ViewData["Title"] = "Cameron's 413 Success Page";
}


<!--Header with my name, followed by a picture of me-->
<h1>Cameron Wilson</h1>

<img src="~/img/utahsXcks.png" />

<!--Paragraph describing what I hope for in the class followed by list of jobs I'm looking for, unordered-->
<p>I hope to feel confident in another programming language. I trust that I will grow in my confidence to create something great out of nothing!</p>

<br />

<p>The jobs I'm looking for:</p>
<ul>
    <li>Technology Consultant</li>
    <li>Data Analyst</li>
    <li>Cyber Security</li>
</ul>



MyFirstWebApp/MyFirstWebApp/Views/Blah/gradeCalc.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model GradeCalcModel;
<!--Form to enter in scores based on each category of the class, accepts user input and calls javascript function-->
<h2>Grade Calculator</h2>
@*will post the user input to the GradeCalcModel*@
<form method="post">
    @*accepts each user input and gets them for the model*@
    <label>% Assignments:</label>
    <input id="assignment" asp-for="Assignments"/><br />
    <label>% Group Project:</label>
    <input id="gproject" asp-for="GroupProject" /><br />
    <label>% Quizzes:</label>
    <input id="quiz" asp-for="Quizzes" /><br />
    <label>% Midterm Exam:</label>
    <input id="midterm" asp-for="MidtermExam" /><br />
    <label>% Final Exam:</label>
    <input id="final" asp-for="FinalExam" /><br />
    <label>% INTEX:</label>
    <input id="intex" asp-for="INTEX" /><br />
    <input id="calc" type="submit" value="Calculate Grade" />
    <br />
    <!--Displays message based on grade calculated-->
    <label id="grade" name="grade"></label>

    @*adds data validation from GradeCalcModel to the form*@
    <div asp-validation-summary="All"/>
</form>

@*adds js program to calculate the grade*@
<script src="js/gradecalc.js"></script>

MyFirstWebApp/MyFirstWebApp/Views/Shared/_Layout.cshtml
@*This is the default layout, the common layout shared across the pages of the application*@

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <!--Customizes the browser window with title and icon for the page, implements bootstrap style-->
    <title>@ViewData["Title"]</title>
    <link href="~/bootstrap/css/style.css" rel="stylesheet" />
    <link rel="icon" href="~/img/icon.png" />
</head>
<body>
    <nav>
        @*navigation bar calls the views attached using tag helpers*@
        <a asp-controller="Blah" asp-action="Index">Home</a>
        <a asp-controller="Blah" asp-action="GradeCalc">Grade Calculator</a>
    </nav>

    <div>
        @RenderBody()
    </div>

    <!--Javascript files are integrated here-->
    <script src="~/lib/jquery/jquery-3.6.3.min.js"></script>
</body>
</html>